sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "000000"

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: yang-springboot-web

  redis:
    host: localhost
    port: 6379
    database: 1

  wechat:
    appid: wx102e7c208839ea85
    secret: d66df2818f478906fc4960e103aa8c9f